### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by otomay** [diogovalentte/homarr-iframes#1]
Nice project! Thx for your work.

It will be really nice to add arm64 support. Most homelabs are hosted in RPIs.

`docker compose up -d` logs:

```
[+] Running 1/0
 ⠋ Container homarr-iframes                                                                                                                     [+] Running 1/2  Recreate0.1s 
 ⠙ Container homarr-iframes                                                                                                                     [+] Running 1/2  Starting0.2s 
 ⠹ Container homarr-iframes                                                                                                                     [+] Running 1/2  Starting0.3s 
 ⠸ Container homarr-iframes                                                                                                                     [+] Running 2/2  Starting0.4s 
 ✔ Container homarr-iframes                                                                                                                                      Started0.4s 
 ! homarr-iframes The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s
 ```

Container logs:
```
exec ./main: exec format error
exec ./main: exec format error
exec ./main: exec format error
exec ./main: exec format error
exec ./main: exec format error
```

**Comment by diogovalentte** [comment]
I published new images, can you test and report back?

**Comment by otomay** [comment]
Thanks, it worked!

![image](https://github.com/diogovalentte/homarr-iframes/assets/54224340/f51f3ea4-6bc2-41e6-8690-6ebce86c785e)

IDK why is showing those white corners, but no prob. I got watchtower, so I'll be updating with your latest releases :D

And a quick note:
In the homarr iframe I could not make it work using my specific private IP (like 192.168.1.xx). Only worked with 127.0.0.1 (homarr and homarr-iframes running on the same server with docker). Maybe put something about it in the docs.

Again: thanks man, keep it up! Loved it!

**Comment by diogovalentte** [comment]
About the white corners, the default theme of the iFrames is light, you can change it to dark too. These themes are made to match the default themes of Homarr. But it seems you're using a background image on Homarr, so neither theme will use your background image and I don't think I can make an iFrame use your dashboard background image.

When I change the background image on my dashboard, it doesn't set the iFrame widget border color to transparent like yours, it can be white or dark depending on the theme I use on Homarr, like below:

![image](https://github.com/diogovalentte/homarr-iframes/assets/49578155/7dc6e4ea-ec37-43bf-bb4d-c9b98c4c5966)
![image](https://github.com/diogovalentte/homarr-iframes/assets/49578155/a2b6fa80-0c22-42e7-8b83-7721c78e9d1b)

Also, I updated the Docker images and the README.md to show how to access it using the private IP. Can you check it and report back?

**Comment by otomay** [comment]
Cool! Dark mode did it:

![image](https://github.com/diogovalentte/homarr-iframes/assets/54224340/8d7893fb-baed-4df4-8b5f-4d939e5b7b2e)

Changed the container to `network_mode: "host"`, but still can't connect with private ip, just local :s

But maybe I'm assuming things wrongly.
I'm not exposing the api ip to public or using a reverse proxy for it.
I was expecting to homarr (exposed to public with reverse proxy) could access the api with private ip (hence both are in the same server) and show the iframe to remote connections. Pihole and qbittorrent integrations works this way, but it may be another logic.

**Comment by diogovalentte** [comment]
> I was expecting to homarr (exposed to public with reverse proxy) could access the api with private ip (hence both are in the same server) and show the iframe to remote connections. Pihole and qbittorrent integrations works this way, but it may be another logic.

It's not Homarr that access the API, it's your browser. When you add an iFrame to your dashboard, the HTML is not fetched from the API by Homarr and then sent to your browser along with the content of the Homarr dashboard. Instead, your browser directly fetches the HTML from the API when it encounters the iframe tag in your Homarr dashboard.

So your browser needs to access the API address directly, maybe you need to change your firewall rules to allow your PC to access the API port on your server. You can check if you can access the API by accessing the route `/v1/health`, it should show the work OK on your browser.

After making sure your browser can access the API, If Homarr is running behind a reverse proxy using a domain and HTTPS, and you add the API URL using HTTP (like `http://192.168.1.44/v1/iframes/cinemark`), your browser will not load the iFrame as you're trying to load HTTP content and Homarr is using HTTPS. You can check the console, maybe there is some error like  `This request has been blocked; the content must be served over HTTPS`.

In this case, you must run the API behind a reverse proxy with a domain and HTTPS (that's how I do it) or run Homarr in HTTP.

Also, I don't get how you're doing it without a reverse proxy or using the server's IP. You said you're using the address `127.0.0.1` on the iFrame widget in Homarr, so your browser should try to get the HTML from your PC, not the server. When I try to use `http://127.0.0.1:8080` on Homarr it doesn't work.

For example, when I'm coding this project, I start the API on my machine and add an iFrame on my dashboard with the address `http://localhost:8080`, so my browser gets the HTML from the API running on my PC. If I stop the API running on my PC, my browser can't get the HTML anymore.

**Comment by otomay** [comment]
Oh I see, now I get how a iframe works. Forget what I said about private ip and localhost. I was thinking in a way on how widgets works in homarr.

For now I'm happy to use only on my home network. In the future I may setup a reverse proxy for it.
Thanks for explaining!
